# Generated by Django 5.2.1 on 2025-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='unique_id',
            field=models.CharField(default='eb9f3abbf26240d4adbe96602aa18084', max_length=255, unique=True),
        ),
    ]
