# Generated by Django 5.2.1 on 2025-06-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_processeddocument_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='keywords',
            new_name='fixed_keywords',
        ),
        migrations.AddField(
            model_name='theme',
            name='dynamic_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='unique_id',
            field=models.CharField(default='050e88b8f265434194ccbbf37a7ecc5e', max_length=255, unique=True),
        ),
    ]
