# Generated by Django 5.2.1 on 2025-06-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_rename_keywords_theme_fixed_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddocument',
            name='unique_id',
            field=models.CharField(default='b3578999f50042f1812116baab065c22', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dynamic_keywords',
            field=models.TextField(blank=True, help_text='Auto-generated keywords from TF-IDF', null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='fixed_keywords',
            field=models.TextField(help_text='15 fixed keywords separated by commas'),
        ),
    ]
